### variabili di configurazione per la compilazione ###
USE_DEBUG = yes
USE_CLANG = no
CFLAGS = -DPBC_SUPPORT
LDFLAGS =
LIBS = m gmp nettle hogweed pbc
PROGS = $(basename $(wildcard test-*.c) $(wildcard attack-*.c) $(wildcard example-*.c)  )
RELEASES = gpl.txt Makefile Makefile.config test-mhz.c test-affinity.c test-rdtsc.c test-rdtscp.c lib-timing.[ch] test-time-syscalls.c test-timing.c test-mpz-init.c test-mpz-add.c test-mpz-mul.c example-fact.c test-mpz-powm.c test-mpz-powm-sec.c test-mpz-pp-powm.c test-mpz-square.c lib-powm.[ch] test-mpz-w-powm.c lib-misc.[ch] test-random.c lib-mesg.[ch] lib-rsa-enc.[ch] test-rsa-enc.c attack-rsa-enc.c lib-rsa-pkcs-enc.[ch] attack-rsa-parity-oracle.c attack-rsa-padding-oracle.c lib-dhke.[ch] test-dhke.c lib-elgamal-enc.[ch] test-elgamal-enc.c attack-elgamal-enc.c test-hashing.c test-cipher-modes.c test-pbc-pairings.c lib-bls-sig.[ch] test-bls-sig.c test-nettle-ecc.c lib-dhke-ecc.[ch] test-dhke-ecc.c 
